version: '3.9'
services:
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - my-network

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    networks:
      - my-network

  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
